import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { FailureClass, Lane } from "./types";

/**
 * Reading the run report the scoreboard writes (`docs/recon-plan.md` R5).
 *
 * The review screen renders `data/recon/eval-report.json` rather than re-running the
 * pipeline per request. That is not a shortcut — it is the same separation the CLIs already
 * keep: **the matcher decides, the scorer measures, the screen renders.** A page that
 * re-matched on every load would be a fourth place the numbers could come from, and the
 * first time it disagreed with `recon:eval` nobody would know which to believe.
 *
 * The file is gitignored, deterministic, and regenerated by `bun run recon:eval`.
 */

export type QueueEntry = {
  lane: Lane;
  outcome: "PROPOSED" | "EXCEPTION";
  rule: string;
  class: FailureClass | null;
  /** Signed paise. Negative on a debit. */
  amount: number;
  left: string[];
  right: string[];
  evidence: string[];
};

export type RunReport = {
  generatedAt: string;
  batch: { dir: string; seed: number; rowsIn: number; records: number; rejected: number };
  timing: { ingestMs: number; matchMs: number; totalMs: number; recordsPerSecond: number };
  headline: {
    precision: number;
    falseMatchRate: number;
    matchRate: number;
    coverage: number;
    exceptionRecall: number;
    escalationRate: number;
  };
  lanes: { lane: Lane; matchRate: number; precision: number; falseMatches: number }[];
  ablation: { model: string; verdict: string } | null;
  queue: QueueEntry[];
};

/**
 * Returns the report, or `null` when there is not one yet.
 *
 * Null rather than a throw: a fresh clone has no `data/` directory, and a screen that
 * crashes because a CLI has not been run is worse than one that says which CLI to run.
 */
export function readRunReport(dir = "data/recon"): RunReport | null {
  try {
    return JSON.parse(readFileSync(join(dir, "eval-report.json"), "utf8")) as RunReport;
  } catch {
    return null;
  }
}
