/**
 * Lesson content is data, not markup.
 *
 * Why: lessons are generated by the `teach` skill, and a typed block union is the
 * only format where a generator cannot quietly produce something off-system. Every
 * block has exactly one renderer, so a lesson physically cannot use a colour, size,
 * or spacing that isn't in the design system. MDX would allow arbitrary JSX and lose
 * that guarantee.
 *
 * Prose fields accept a tiny inline markdown subset: `code`, **bold**, _italic_,
 * [text](href). Nothing else — see components/learning/markdown.tsx.
 */

export type Block =
  /** A section heading. Anchors the progress indicator and the on-page nav. */
  | { kind: "heading"; text: string; id: string }
  /** One or more paragraphs of prose. */
  | { kind: "prose"; text: string }
  /** Bulleted or numbered list. */
  | { kind: "list"; ordered?: boolean; items: string[] }
  /** Fenced code. `file` renders as a caption so lessons can point at real paths. */
  | { kind: "code"; lang: string; file?: string; code: string }
  /** Comparison table. First row of `rows` is data, not a header. */
  | { kind: "table"; head: string[]; rows: string[][] }
  /** Mermaid diagram, click-to-expand. `caption` explains what to look at. */
  | { kind: "diagram"; mermaid: string; caption?: string }
  /**
   * A generated illustration — for a metaphor a box-and-arrow diagram cannot
   * carry. Produced by `scripts/gen-image.py`; `src` is a path under /public.
   * Structural things stay diagrams: this is not an alternative to Mermaid.
   */
  | {
      kind: "image";
      src: string;
      alt: string;
      caption?: string;
      width: number;
      height: number;
    }
  /** An aside. `note` for context, `warn` for a trap, `key` for the load-bearing idea. */
  | { kind: "callout"; tone: "note" | "warn" | "key"; title?: string; text: string }
  /** A pointer into the real repo — the whole reason these lessons aren't generic. */
  | { kind: "source"; path: string; lines?: string; note: string }
  /** External documentation worth reading. */
  | { kind: "docs"; links: { label: string; href: string; note?: string }[] }
  /**
   * The hands-on section — a real task in THIS repo, not a sandbox exercise.
   * Akshay implements it; the criteria are what the review is run against, so
   * they must be things a reviewer can actually check, not "understand X".
   */
  | {
      kind: "task";
      /** Matches a task id in learning/path.ts, e.g. "A3". */
      taskId: string;
      goal: string;
      /** Real paths he will create or change. */
      files: string[];
      parts: { title: string; steps: string[] }[];
      /** Reviewed against these, in order. */
      criteria: string[];
    }
  /** Retrieval practice. Rendered after the challenge, never before. */
  | {
      kind: "quiz";
      question: string;
      options: string[];
      answer: number;
      /** Shown on a wrong answer. Explain the mechanism, don't just restate. */
      explain: string;
    };

export type Lesson = {
  slug: string;
  /** Two-digit ordering key, shown in the topic list. */
  n: string;
  title: string;
  /** One line. Appears in the topic list under the title. */
  summary: string;
  /** Minutes, honestly estimated. */
  minutes: number;
  blocks: Block[];
};

export type Topic = {
  slug: string;
  title: string;
  /** One line describing the arc of the whole topic. */
  summary: string;
  /** Phase in learning/path.ts this topic teaches, if any. */
  phase?: string;
  lessons: Lesson[];
};


/* ── The learning path ──────────────────────────────────────────────────────
   The dev plan and the curriculum are the same object. Every task is a real
   change to this repo; the lesson attached to it is what you read before you
   start. Status is stored here, in git, because Claude moves tasks along as
   the review passes — there is no second source of truth to drift.
   ───────────────────────────────────────────────────────────────────────── */

export type TaskStatus =
  /** Not reached yet. */
  | "todo"
  /** Lesson written and ready to read. */
  | "learn"
  /** Akshay is implementing. */
  | "building"
  /** Implemented, waiting on Claude's review. */
  | "review"
  /** Reviewed and accepted. */
  | "done";

export type Task = {
  /** Short stable id, e.g. "A3". Referenced by a lesson's task block. */
  id: string;
  title: string;
  /** One line: what exists after this task that did not before. */
  outcome: string;
  status: TaskStatus;
  /** The lesson to read first, as [topicSlug, lessonSlug]. */
  lesson?: [string, string];
  /** Task ids that must be done first. */
  needs?: string[];
  /** What this task is really teaching. */
  teaches: string;
};

export type Phase = {
  id: string;
  title: string;
  /** What the phase is for, in one line. */
  goal: string;
  /** Written out only for the phase we are actually in. */
  detailed: boolean;
  tasks: Task[];
};
